# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
  
  lane :tests do
    run_tests(scheme: "Pet Care")
  end
  
 lane :register do
    produce(
    username: 'pankaj.excelsior@gmail.com',
    app_identifier: 'com.me.petcareapp',
    app_name: 'Pet Care',
    language: 'English',
    app_version: '1.0',
    sku: '123'
    )
  end
  
  lane :beta do
    setup_ci if ENV['CI']
    match(type: 'appstore')
    build_app
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
  
end
